# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:42
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0010_auto_20170622_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='commandesATraiter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('live', 'LIVE'), ('catchup', 'CATCHUP'), ('startover', 'STARTOVER'), ('vodplayout', 'VOD PLAYOUT'), ('vodprepackaged', 'VOD PREPACKAGED'), ('ntc', 'NTC'), ('npvr', 'nPVR')], default='catchup', max_length=57),
        ),
    ]
