# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0012_auto_20170622_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='commandesATraiter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('live', 'LIVE'), ('catchup', 'CATCHUP'), ('startover', 'STARTOVER'), ('vodplayout', 'VOD PLAYOUT'), ('vodprepackaged', 'VOD PREPACKAGED'), ('ntc', 'NTC'), ('npvr', 'nPVR')], default='live', max_length=57),
        ),
    ]
