# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:08
from __future__ import unicode_literals

import abstract.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0013_auto_20170622_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d', validators=[abstract.extra.validate_file_extension])),
            ],
        ),
        migrations.DeleteModel(
            name='MyApp',
        ),
    ]
