# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:27
from __future__ import unicode_literals

import abstract.extra
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0015_auto_20170622_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='VSPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MISTRAL', max_length=250, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de creation')),
            ],
        ),
        migrations.RemoveField(
            model_name='listedepod',
            name='link',
        ),
        migrations.AddField(
            model_name='namepod',
            name='link',
            field=models.CharField(default='strm.podX.manager.cdvr.orange.fr', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='schemadash',
            field=models.FileField(upload_to='schemas/dash/%Y/%m/%d', validators=[abstract.extra.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='schemasmooth',
            field=models.FileField(upload_to='schemas/smooth/%Y/%m/%d', validators=[abstract.extra.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='namechaine',
            name='description',
            field=models.TextField(default='Description de la Chaine'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vspp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abstract.VSPP'),
        ),
    ]
