# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0016_auto_20170623_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Requ\xeate API VOD', 'verbose_name_plural': 'Requ\xeates API VOD'},
        ),
    ]
