# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0018_auto_20170623_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vspp',
            options={'verbose_name': 'VSPP ', 'verbose_name_plural': 'Les VSPPs de Tests '},
        ),
    ]
